In [1]:
import numpy as np

In [2]:
mark_list = [82,95,90,80,85,72]
mark_array = np.array(mark_list)

In [3]:
print(mark_array)

[82 95 90 80 85 72]


In [48]:
np.random.rand(3,3)

array([[0.58822557, 0.66998116, 0.46957007],
       [0.66644029, 0.52984154, 0.09563714],
       [0.8579798 , 0.18347101, 0.27975032]])

In [125]:
np.random.random(30)

array([0.13860297, 0.1044753 , 0.61368438, 0.29377924, 0.82847196,
       0.84480102, 0.57282655, 0.75552671, 0.97589409, 0.02345334,
       0.10311741, 0.54121775, 0.10339506, 0.05601659, 0.14450311,
       0.19256817, 0.52356636, 0.76245299, 0.79241998, 0.28671144,
       0.81446822, 0.1929128 , 0.54868956, 0.31685509, 0.87014966,
       0.61948043, 0.69679419, 0.65136263, 0.35286826, 0.06937717])

In [123]:
np.random.randn(4,3)

array([[ 2.06366679, -0.82371654, -0.23308945],
       [-0.46482093, -0.81136501,  1.74702746],
       [ 1.11900687,  0.92811959, -1.59562405],
       [-0.52282363, -0.95149967, -0.33401513]])

In [55]:
np.random.randint(1,101,100)

array([ 30,  70,  89,  75,  62,  46,  16,  25,  36,  79,  63,  56,  86,
        29,  33,  23,  72,   7,  88,  17,  72,  88,  69,  15,  66,  91,
        88,  87,  75,  98,  51,  17,   9,  87,  20,  51,  43,  73,  83,
        14,  95,  67,  74,  22,  20,   7,  25,  44,  29,  42,   3,  70,
        46,  98,  55,  64,  90,  19,  78,  39, 100,  25,  53,  80,   4,
         8,  23,  14,  75,  16,  75,  35,  30,  50,  19,   7,  60,  69,
        94,  54,  30,  86,  55,  44,  70,  28,  20,  51,  70,  96,  16,
        13,  80,  54,  78,  71,  78,  95,   8,  94])

In [67]:
np.random.randint(1,10)

7

In [70]:
array = np.arange(5,100,5)

In [71]:
print(array)

[ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [77]:
arr = np.arange(100,0,-1)

In [78]:
print(arr)


[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]


In [128]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [90]:
ap = np.zeros(10,int)

In [91]:
print(ap)

[0 0 0 0 0 0 0 0 0 0]


In [93]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [96]:
matrix = np.empty((3,3),dtype = int)
print(matrix)

[[1696097520        432          0]
 [   5570652       1128          0]
 [       768      32761    6815860]]


In [97]:
matrix = np.full((3,3),fill_value = 11)

In [98]:
print(matrix)

[[11 11 11]
 [11 11 11]
 [11 11 11]]


In [100]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [101]:
np.eye(4,5,0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [102]:
np.eye(4,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [103]:
np.eye(4,5,-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [104]:
a = np.arange(1,21)

In [105]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [107]:
a.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [108]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [119]:
sample_array = np.arange(0,11)

In [120]:
sample_array[6]

6

In [121]:
sample_array[:3]

array([0, 1, 2])

In [1]:
text = 'i love python'
text[::-1][-3]

'l'